Application:
  observe-folders: ["D:/SibCenter/ProjectVisitor/test/testApplication",
                    "D:/SibCenter/ProjectVisitor/test/testApplication2"]

ExportersFormats:
  ProjectExportVisitor:
    formats: [".doc", ".docx", ".pdf"]
  PythonExportVisitor:
    formats: [".py", ".txt"]

BD:
  mysql:
    host: "localhost"
    port: "5455"
    password: "infini_rag_flow"
  elastic:
    host: "localhost"
    port: "9221"
    password: "infini_rag_flow"